#!/bin/bash
#SBATCH --partition=ecsall
#SBATCH --account=ecsstaff
#SBATCH --time=48:00:00
#SBATCH --ntasks=1
#SBATCH --gres=gpu:1
#SBATCH -N 1 -n 8


# python train_unet_hist.py -g 0 -b 6 -d CRAG -f 4
# python -u train_unet_hist.py -g 0 -b 8 -d Kumar -f 4
# python -u train_unet_hist.py -g 0 -b 24 -d BCSS -f 4


# python -u train_unet_e_hist.py -g 0 -b 8 -d Kumar
python -u train_unet_e_hist.py -g 0 -b 12 -d BCSS -f 2


